code:
  image: busybox
  volumes:
    - ./code:/usr/src/myapp

cache:
  image: busybox
  # build: ./dfiles/data
  volumes:
    - ./cache:/data

node:
  # image: node
  build: ./dfiles/node
  volumes_from:
    - cache
    - code
  links:
    - mongo:mongo
  ports:
    - "8080:8080"
    - "5858:5858"
  working_dir: /usr/src/myapp
  environment:
    node-inspector_web-host: 0.0.0.0
    node-inspector_save-live-edit: 'true'
  user: ac

mongo:
    image: mongo
    volumes:
        - ./db:/data/db

mongo-express:
    image: knickers/mongo-express
    links:
        - mongo:mongo
    ports:
        - "8081:8081"
