node:
  image: node
  # build: ./dfiles/node
  volumes:
    - ./src:/usr/src/myapp
    - ./cache:/data
  links:
    - mongo:mongo
  ports:
    - "8080:8080"
  working_dir: /usr/src/myapp
  environment:
    node-inspector_web-host: 0.0.0.0
    node-inspector_save-live-edit: 'true'
    PORT: 8080
  # user: ac

mongo:
    image: mongo:3.2
    volumes:
        - ./db:/data/db

mongo-express:
    image: knickers/mongo-express
    links:
        - mongo:mongo
    ports:
        - "8081:8081"
