data:  
  build: dfiles/data
  volumes:
    - code:/usr/src/myapp

cache:
  build: dfiles/data
  volumes:
    - cache:/data

node:  
  build: dfiles/node
  volumes_from:
    - data
    - cache
  ports:
    - "7070:7070"
  working_dir: /usr/src/myapp
