code:
  image: busybox
  volumes:
    - ./code:/usr/src/myapp

cache:
  image: busybox
  # build: ./dfiles/data
  volumes:
    - ./cache:/data

node:
  # build: ./dfiles/node
  image: node
  volumes_from:
    - cache
    - code
  links:
    - mongo:mongo
  # ports:
  #   - "7070:7070"
  working_dir: /usr/src/myapp


mongo:
    image: mongo
    volumes:
        - ./db:/data/db
